version: '3.4'

services:
  jsfprimeface:
    image: jsfprimeface
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_TYPE=MYSQL
      - DB_NAME=${DB_NAME:-jsfprimeface}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./DEBUG/tomcat/logs:/usr/local/tomcat/logs
